/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class FstEnum { }
export declare class FstJsReader {
  /** Constructor: Create a new FST reader */
  constructor(file: string)
  /** Read all variable names from the FST file */
  read(): string
  /** Get the value of a variable at a specific time */
  getVarValueAtTime(varName: string, time: number): number
  getVarEnumValueAtTime(varName: string, enumName: string, time: number): string
  /** Get the next time change for a variable */
  getNextTimeChange(varName: string, startTime: number): number
  /** Get the timescale of the FST file */
  getTimescale(): string
  /** Get the timezero of the FST file */
  getTimezero(): number
  /** Get metadata about the FST file */
  getMetadata(): object
  /** Get variable information */
  getVariableInfo(varName: string): object
}
